---

# ANSIBLE
ansible_min_version: '2.9'

# CERTBOT
certbot_auto_renew_options: --agree-tos --no-self-upgrade --pre-hook "service nginx stop" --post-hook "service nginx start"
certbot_auto_renew_user: root
certbot_certs:
  - email: "{{ certbot_admin_email }}"
    domains:
      - "{{ inventory_hostname }}"
certbot_create_if_missing: yes
certbot_install_from_source: yes

# COLLECTIONSPACE
collectionspace_tomcat_version: apache-tomcat-8.5.40
collectionspace_version: '5.2'

# ELASTICSEACH
elasticsearch_version: '5.x'

# NGINX
nginx_remove_default_vhost: true

# POSTGRES
postgresql_users:
  - name: csadmin
    password: "{{ collectionspace_csadmin_password }}"
    role_attr_flags: 'SUPERUSER,INHERIT,NOCREATEDB,NOCREATEROLE,NOREPLICATION'
    state: present
