---

- hosts: all
  gather_facts: true
  become: yes

  pre_tasks:
    - import_tasks: includes/version.yml
    - name: Install packages
      apt:
        pkg:
          - acl
          - htop
          - gpg
          - python3-psycopg2
          - "{{ java_package }}"
        update_cache: yes
      tags:
        - apt

  roles:
    - role: postgresql
      tags: ['db', 'postgres']
    - role: elasticsearch
      tags: ['es', 'search']
    - role: collectionspace
      tags: ['collectionspace', 'cspace']
    - role: nginx
      tags: ['nginx', 'web']
    - role: certbot
      tags: ['certbot', 'certs']
      when: certbot_certs | length > 0

  tasks:
    - name: Create CollectionSpace vhost config
      template:
        src: templates/cspace.conf.j2
        dest: "/etc/nginx/sites-enabled/cspace.conf"
        mode: 0644
      notify: restart nginx
      tags:
        - nginx
        - vhost
        - web
