---

- hosts: all
  gather_facts: true
  become: yes

  pre_tasks:
    - import_tasks: includes/version.yml

  roles:
    - role: postgresql
      tags: ['db', 'postgres']
    - role: elasticsearch
      tags: ['es', 'search']
    - role: collectionspace
      tags: ['collectionspace', 'cspace']
    - role: nginx
      tags: ['nginx', 'web']
    - role: certbot
      tags: ['certbot', 'certs']

  tasks:
    - name: Create CollectionSpace vhost config
      template:
        src: templates/cspace.conf.j2
        dest: "/etc/nginx/sites-enabled/cspace.conf"
        mode: 0644
      notify: restart nginx
      tags:
        - nginx
        - vhost
        - web
