---

- src: https://github.com/geerlingguy/ansible-role-certbot.git
  name: certbot
  version: 4.1.0

- src: https://github.com/geerlingguy/ansible-role-elasticsearch
  name: elasticsearch
  version: 4.2.0

- src: https://github.com/geerlingguy/ansible-role-nginx
  name: nginx
  version: 3.1.0

- src: https://github.com/geerlingguy/ansible-role-postgresql
  name: postgresql
  version: 3.1.1
