---

- hosts: all
  gather_facts: true
  become: yes

  handlers:
    - name: restart ssh
      service:
        name: ssh
        state: restarted

  pre_tasks:
    - import_tasks: includes/version.yml
    - import_tasks: includes/security.yml
      tags:
        - security
