---

collectionspace_allocated_ram: "2048m"
collectionspace_csadmin_password: False
collectionspace_environment:
  "ANT_OPTS": "-Xmx{{ collectionspace_allocated_ram }}"
  "CATALINA_HOME": "/opt/collectionspace/server"
  "CATALINA_OPTS": "-Xmx{{ collectionspace_allocated_ram }} -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Duser.timezone=UTC"
  "CATALINA_PID": "/opt/collectionspace/server/bin/tomcat.pid"
  # Enable Core by default, we do not recommend changing this
  "CSPACE_CORE_CREATE_DISABLED_OPT": "false"
  "CSPACE_INSTANCE_ID": "_default"
  "CSPACE_JEESERVER_HOME": "/opt/collectionspace/server"
  "DB_CSADMIN_PASSWORD": "{{ collectionspace_csadmin_password }}"
  "DB_HOST": "localhost"
  "DB_PORT": "5432"
  "DB_NUXEO_PASSWORD": "{{ collectionspace_csadmin_password }}"
  "DB_CSPACE_PASSWORD": "{{ collectionspace_csadmin_password }}"
  "DB_READER_PASSWORD": "{{ collectionspace_csadmin_password }}"
  "JAVA_HOME": "/usr/lib/jvm/java-8-openjdk-amd64/"
  "JEE_PORT": "8180"
  "MAVEN_OPTS": "-Xmx{{ collectionspace_allocated_ram }}"
collectionspace_force_build: False
collectionspace_tenant: core
collectionspace_tomcat_version: apache-tomcat-8.5.51
collectionspace_version: '6.0'
