---

- name: Starting build process
  debug:
    msg: Building collectionspace (this may take a while) ...

- name: Stop CollectionSpace before build
  service:
    name: collectionspace
    state: stopped
  when: >
    ansible_facts.services['collectionspace.service'] is defined and
    ansible_facts.services['collectionspace.service']['state'] == 'running'

- name: Build CollectionSpace
  shell: >
    cd /opt/collectionspace/services && mvn clean install -DskipTests && \
    cd /opt/collectionspace/application && mvn clean install -DskipTests && \
    cd /opt/collectionspace/services && ant undeploy deploy create_db import && \
    touch /opt/collectionspace/build/build.{{ ansible_date_time.epoch }}
  args:
    executable: /bin/bash
  async: 7200
  poll: 0
  become: true
  become_user: collectionspace

- name: "Wait for CollectionSpace build (build.{{ ansible_date_time.epoch }}"
  wait_for:
    path: "/opt/collectionspace/build/build.{{ ansible_date_time.epoch }}"
    timeout: 7200
