---

- name: Starting build process
  debug:
    msg: Building collectionspace (this may take a while) ...

- name: Stop CollectionSpace before build
  service:
    name: collectionspace
    state: stopped
  when: >
    ansible_facts.services['collectionspace.service'] is defined and
    ansible_facts.services['collectionspace.service']['state'] == 'running'

- name: Build CollectionSpace services layer
  shell: >
    cd /opt/collectionspace/services && mvn clean install -DskipTests
  args:
    executable: /bin/bash
  become: true
  become_user: collectionspace

- name: Build CollectionSpace application layer
  shell: >
    cd /opt/collectionspace/application && mvn clean install -DskipTests
  args:
    executable: /bin/bash
  become: true
  become_user: collectionspace

- name: Build CollectionSpace deployment and setup authz database
  shell: >
    cd /opt/collectionspace/services && ant undeploy deploy create_db import
  args:
    executable: /bin/bash
  become: true
  become_user: collectionspace

# this is a marker that at least the initial build was completed
- name: Create bootstrap file
  file:
    path: "/opt/collectionspace/build/bootstrap"
    state: touch
  when: not bootstrap.stat.exists
