---

- name: Download the CollectionSpace server
  unarchive:
    src: "{{ collectionspace_server_url }}"
    dest: /opt/collectionspace
    remote_src: yes
    owner: collectionspace
    group: collectionspace
  register: server

- name: Create a symlink for the server
  file:
    src: "/opt/collectionspace/{{ collectionspace_tomcat_version }}"
    dest: /opt/collectionspace/server
    state: link
    owner: collectionspace
    group: collectionspace
  when: server.changed

- name: Download the CollectionSpace applications
  git:
    repo: "https://github.com/collectionspace/{{ item }}"
    dest: "/opt/collectionspace/{{ item }}"
    version: "{{ collectionspace_revision }}"
    force: yes
  with_items:
    - application
    - services
  register: source

- name: Download the CollectionSpace public gateway
  get_url:
    url: "{{ collectionspace_gateway_url }}"
    dest: "/opt/collectionspace/server/webapps/gateway.war"
    owner: collectionspace
    group: collectionspace

- name: Ensure CollectionSpace user ownernship
  file:
    path: /opt/collectionspace
    state: directory
    recurse: yes
    owner: collectionspace
    group: collectionspace
