---

- name: Create public gateway configuration file
  template:
    src: gateway.yml.j2
    dest: /opt/collectionspace/server/lib/gateway.yml
    owner: collectionspace
    group: collectionspace
    mode: '0644'
  tags:
    - gateway

- name: Create public browser single page app
  template:
    src: browser.html.j2
    dest: "{{ item }}"
    owner: collectionspace
    group: collectionspace
    mode: '0644'
  with_items:
    - /opt/collectionspace/browser/index.html # nginx
    - /opt/collectionspace/server/webapps/ROOT/index.html # tomcat
  tags:
    - browser

- name: Enable ElasticSearch
  lineinfile:
    path: /opt/collectionspace/server/nuxeo-server/config/nuxeo.properties
    regexp: '^elasticsearch.enabled='
    line: elasticsearch.enabled=true
    owner: collectionspace
    group: collectionspace
