---

- name: Create CollectionSpace service file
  template:
    src: service.j2
    dest: /etc/systemd/system/collectionspace.service

- name: Start and enable CollectionSpace
  systemd:
    name: collectionspace
    state: started
    enabled: yes
    daemon-reload: yes
  register: start
