---

- name: Create CollectionSpace service file
  template:
    src: service.j2
    dest: "{{ collectionspace_service_path }}"

- name: Start and enable CollectionSpace
  systemd:
    name: collectionspace
    state: started
    enabled: yes
    daemon-reload: yes
  register: start
