---

- name: Create CollectionSpace service file
  template:
    src: service.j2
    dest: "{{ collectionspace_service_path }}"
    mode: '0644'

- name: Start and enable CollectionSpace
  systemd:
    name: collectionspace
    state: started
    enabled: true
    daemon-reload: true
  register: start
