---

- name: Ensure Collectionspace group exists
  group:
    name: collectionspace
    state: present

- name: Ensure collectionspace user exists
  user:
    name: collectionspace
    state: present
    group: collectionspace
    shell: /bin/bash

- name: Set CollectionSpace general environment variables
  blockinfile:
    path: /home/collectionspace/.bashrc
    block: "{{ lookup('template', 'env.j2') }}"
    owner: collectionspace
    group: collectionspace
    marker: "# {mark} ANSIBLE MANAGED BLOCK CSPACE GENERAL ENV"
  no_log: true

- name: Set CollectionSpace tenant environment variables
  blockinfile:
    path: /home/collectionspace/.bashrc
    block: "{{ lookup('template', 'tenants.j2') }}"
    owner: collectionspace
    group: collectionspace
    marker: "# {mark} ANSIBLE MANAGED BLOCK CSPACE TENANT ENV"
  register: tenants
