---

- name: Ensure Collectionspace group exists
  group:
    name: collectionspace
    state: present

- name: Ensure collectionspace user exists
  user:
    name: collectionspace
    state: present
    group: collectionspace
    shell: /bin/bash

- name: Set CollectionSpace user environment variables
  blockinfile:
    path: /home/collectionspace/.bashrc
    block: "{{ lookup('template', 'user_env.j2') }}"
    owner: collectionspace
    group: collectionspace
    marker: "# {mark} ANSIBLE MANAGED BLOCK CSPACE ENV"
  no_log: true
